### ISSUE TITLE
If App is manually Stopped you can bypass Focus

### ISSUE THREAD

**Issue by WreckingBANG** [akaMrNagar/Mindful#94] opened 2024-10-06 10:43 UTC
**Describe the bug**
If i manually Stop the App via the Force Stop option in the AppInfo Section, the App does not restart again and you can override the App Blockade. Once i manually restart the App everything is back to normal.

**To Reproduce**
1. Setup a Focus Phase for any time
2. Exit the App
3. Long Press App Icon
4. Click AppInfo
5. Force Stop App
6. Access any App that should not be accessed in the Focus Time

**Expected behavior**

The App should immediately restart after you press Force Stop

**Additional context**
- Device: Pixel 7 Pro
- OS: Android 14 (GrapheneOS, No GPlay)
- Version: 0.0.14+114

**Log file**
[mindful_crash_logs.json](https://github.com/user-attachments/files/17268965/mindful_crash_logs.json)

**Comment by akaMrNagar** [comment] 2024-10-06 12:59
This is intended functionality in android and cannot be influenced by external app. There is only one thing we can do we can implement Admin system so that once the admin is activated android automatically disables force stop and clear data button on app info page.


I am closing this issue as this is not a bug  but i have this feature planned for future in parental control including local biometric authentication.

**Comment by WreckingBANG** [comment] 2024-10-07 16:07
> There is only one thing we can do we can implement Admin system so that once the admin is activated android automatically disables force stop and clear data button on app info page.
> 

That would be awesome!

**Closed** 2024-12-01 14:10 UTC
Labels: bug

**Comment by WreckingBANG** [comment] 2024-12-01 15:59
Thank you!
